server:
  port: 8080
spring:
  application:
    name: 'pgvector'
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: Admin@123
  ai:
    ollama:
      base-url: 'http://localhost:11434'
      embedding:
        enabled: true
        model: 'mxbai-embed-large'
      chat:
        model: 'llama3.2'
        enabled: true
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1024 #1536 is the default embedding dimension
        remove-existing-vector-store-table: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
